services:
  - type: web
    name: sighh-lms
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: BASE_URL
        sync: false
# cronJobs:
#   - name: lembretes
#     schedule: "0 12 * * *"
#     command: curl -s $RENDER_EXTERNAL_URL/cron/reminders
